package no.nav.sokos.spk.mottak.database

import java.time.LocalDate

data class InTransaction(
    val id: Int,
    val filInfoId: Int,
    val belopType: String,
    val art: String,
    val gjelderId: String,
    val status: String,
    val utbetalesTil: String,
    val datoFomStr: String,
    val datoFom: LocalDate,
    val datoTomStr: String,
    val datoTom: LocalDate,
    val refTransId: String,
    val belopStr: String,
    val belop: Int,
    val tekstKode: String,
    val recType: String,
    val transId: String,
    val datoAnviserStr: String,
    val datoAnviser: LocalDate,
    val avsender: String,
    val saldoStr: String,
    val saldo: Int,
    val prioritetStr: String,
    val prioritet: LocalDate,
    val kid: String,
    val trekkansvar: String,
    val gradStr: String,
    val grad: Int,
    val behandlet: String,
    val datoOpprettet: String,
    val opprettetAv: String,
    val datoEndret: String,
    val endretAv: String,
    val versjon: String,
    var feiltekst: String,
)