apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-spk-mottak-qx
  namespace: okonomi
  labels:
    team: okonomi
spec:
  image: "{{{ image }}}"
  port: 8080
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  liveness:
    path: /internal/isAlive
    initialDelay: 5
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/isReady
    initialDelay: 5
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      memory: 4096Mi
    requests:
      cpu: 2000m
      memory: 4096Mi
  ingresses:
    - https://sokos-spk-mottak-qx.intern.dev.nav.no
  prometheus:
    enabled: true
    path: /internal/metrics
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  accessPolicy:
    inbound:
      rules:
        - application: azure-token-generator
          namespace: aura
          cluster: dev-gcp
  webproxy: true
  vault:
    enabled: true
  filesFrom:
    - secret: db2license
      mountPath: /var/run/secrets/db2license
    - secret: spk-sftp-private-key
      mountPath: /var/run/secrets/spk-sftp-private-key
  envFrom:
    - secret: spk-sftp-creds
    - secret: oppdrag-qx-credentials
  env:
    - name: USE_AUTHENTICATION
      value: "true"

    # DB2
    - name: DATABASE_HOST
      value: "155.55.1.82"
    - name: DATABASE_PORT
      value: "5025"
    - name: DATABASE_NAME
      value: "QDB2"
    - name: DATABASE_SCHEMA
      value: "MO611QX"

    # Postgres
    - name: POSTGRES_HOST
      value: b27dbvl034.preprod.local
    - name: POSTGRES_PORT
      value: "5432"
    - name: POSTGRES_NAME
      value: sokos-spk-mottak-qx
    - name: VAULT_MOUNTPATH
      value: postgresql/preprod-fss/

    # SFTP
    - name: SFTP_SERVER
      value: b31apvl069.oera-q.local
    - name: SFTP_PORT
      value: "22"
    - name: SFTP_PRIVATE_KEY_FILE_PATH
      value: /var/run/secrets/spk-sftp-private-key/spk-sftp-private-key

    # Pensjon-fullmakt-q2
    - name: PENSJON_REPRESENTASJON_URL
      value: https://pensjon-representasjon-q2.intern.dev.nav.no
    - name: PENSJON_REPRESENTASJON_SCOPE
      value: dev-fss.pensjon-person.pensjon-representasjon-q2

    # DB-SCHEDULER
    - name: READ_AND_PARSEFILE_CRON_PATTERN
      value: "* 30 * * * *"
    - name: VALIDATE_TRANSAKSJON_CRON_PATTERN
      value: "* 5 * * * *"