apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-spk-mottak-qx
  namespace: okonomi
  labels:
    team: okonomi
spec:
  image: "{{{ image }}}"
  port: 8080
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  liveness:
    path: /internal/isAlive
    initialDelay: 5
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/isReady
    initialDelay: 5
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      memory: 4096Mi
    requests:
      cpu: 2000m
      memory: 4096Mi
  ingresses:
    - https://sokos-spk-mottak-qx.intern.dev.nav.no
  prometheus:
    enabled: true
    path: /internal/metrics
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  accessPolicy:
    inbound:
      rules:
        - application: azure-token-generator
          namespace: aura
          cluster: dev-gcp
  webproxy: true
  vault:
    enabled: true
  filesFrom:
    - secret: db2license
      mountPath: /var/run/secrets/db2license
    - secret: spk-sftp-private-key
      mountPath: /var/run/secrets/spk-sftp-private-key
  envFrom:
    - secret: spk-sftp-qx-creds
    - secret: oppdrag-qx-credentials
    - secret: sokos-spk-mottak-mq-credentials
  env:
    - name: USE_AUTHENTICATION
      value: "true"

    # OpenTelemetry
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: "https://elastic-apm.adeo.no"
    - name: OTEL_METRICS_EXPORTER
      value: "otlp"
    - name: OTEL_LOGS_EXPORTER
      value: "none"
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: "service.name=sokos-spk-mottak,service.version=sokos-spk-mottak,deployment.environment=qx"
    - name: OTEL_TRACES_EXPORTER
      value: "otlp"

    # DB2
    - name: DATABASE_HOST
      value: "155.55.1.82"
    - name: DATABASE_PORT
      value: "5025"
    - name: DATABASE_NAME
      value: "QDB2"
    - name: DATABASE_SCHEMA
      value: "MO611QX"

    # Postgres
    - name: POSTGRES_HOST
      value: b27dbvl034.preprod.local
    - name: POSTGRES_PORT
      value: "5432"
    - name: POSTGRES_NAME
      value: sokos-spk-mottak-qx
    - name: VAULT_MOUNTPATH
      value: postgresql/preprod-fss/

    # MQ
    - name: MQ_HOSTNAME
      value: mqls02.preprod.local
    - name: MQ_PORT
      value: "1413"
    - name: MQ_QUEUE_MANAGER_NAME
      value: MQLS02
    - name: MQ_CHANNEL_NAME
      value: Q1_MOT
    - name: MQ_UTBETALING_QUEUE_NAME
      value: QA.Q1_231.OB04_OPPDRAG_MOT_XML
    - name: MQ_UTBETALING_REPLY_QUEUE_NAME
      value: QA.Q1_MOT.UTBET_REQUEST_QUE_MOT_BATCH_REPLY
    - name: MQ_TREKK_QUEUE_NAME
      value: QA.Q1_231.OB04_TREKK_MOT_XML
    - name: MQ_TREKK_REPLY_QUEUE_NAME
      value: QA.Q1_MOT.TREKK_REQUEST_QUE_MOT_BATCH_REPLY

    # SFTP
    - name: SFTP_SERVER
      value: b31apvl069.oera-q.local
    - name: SFTP_PORT
      value: "22"
    - name: SFTP_PRIVATE_KEY_FILE_PATH
      value: /var/run/secrets/spk-sftp-private-key/spk-sftp-private-key

    # DB-SCHEDULER
    - name: READ_AND_PARSEFILE_CRON_PATTERN
      value: "* * 7_17 * * *"
    - name: VALIDATE_TRANSAKSJON_CRON_PATTERN
      value: "* * 7-17 * * *"