apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-spk-mottak
  namespace: okonomi
  labels:
    team: okonomi
spec:
  image: "{{{ image }}}"
  port: 8080
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 75
  liveness:
    path: /internal/isAlive
    initialDelay: 5
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/isReady
    initialDelay: 5
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      memory: 4096Mi
    requests:
      cpu: 2000m
      memory: 4096Mi
  ingresses:
    - https://sokos-spk-mottak.intern.nav.no
    - https://sokos-spk-mottak.prod-fss-pub.nais.io
  prometheus:
    enabled: true
    path: /internal/metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - NAVident
  accessPolicy:
    inbound:
      rules:
        - application: sokos-utbetalingsportalen
          namespace: okonomi
          cluster: prod-gcp
        - application: pensjon-pen
          namespace: pensjondeployer
          cluster: prod-fss
    outbound:
      rules:
        - application: logging
          namespace: nais-system
  webproxy: true
  vault:
    enabled: true
  filesFrom:
    - secret: db2license
      mountPath: /var/run/secrets/db2license
    - secret: spk-sftp-private-key
      mountPath: /var/run/secrets/spk-sftp-private-key
  envFrom:
    - secret: spk-sftp-credentials
    - secret: spk-mottak-oppdrag-credentials
    - secret: spk-mottak-mq-credentials
  env:
    - name: USE_AUTHENTICATION
      value: "true"

    # DB2
    - name: DATABASE_HOST
      value: "155.55.1.78"
    - name: DATABASE_PORT
      value: "5021"
    - name: DATABASE_NAME
      value: "DB2"
    - name: DATABASE_SCHEMA
      value: "MO611P"

    # Postgres
    - name: POSTGRES_HOST
      value: A01DBVL036.adeo.no
    - name: POSTGRES_PORT
      value: "5432"
    - name: POSTGRES_NAME
      value: sokos-spk-mottak
    - name: VAULT_MOUNTPATH
      value: postgresql/prod-fss/

    # MQ Sjekk om alle disse verdiene er riktig
    - name: MQ_HOSTNAME
      value: mpls02.adeo.no
    - name: MQ_PORT
      value: "1414"
    - name: MQ_QUEUE_MANAGER_NAME
      value: MPLS02
    - name: MQ_CHANNEL_NAME
      value: P_MOT
    - name: MQ_UTBETALING_QUEUE_NAME
      value: QA.P231.OB04_OPPDRAG_MOT_XML
    - name: MQ_UTBETALING_REPLY_QUEUE_NAME
      value: QA.P_MOT.UTBET_REQUEST_QUE_MOT_BATCH_REPLY
    - name: MQ_TREKK_QUEUE_NAME
      value: QA.P231.OB04_TREKK_MOT_JSON
    - name: MQ_TREKK_REPLY_QUEUE_NAME
      value: QA.P_MOT.TREKK_REQUEST_QUE_MOT_BATCH_REPLY
    - name: MQ_AVREGNINGSGRUNNLAG_QUEUE_NAME
      value: QA.P_MOT.AVREGNINGSGRUNNLAG_MOT_JSON
    - name: MQ_AVSTEMMING_QUEUE_NAME
      value: QA.P234.OB29_AVSTEMMING_XML
    - name: MQ_BATCH_SIZE
      value: "200"
    - name: MQ_LISTENER_ENABLED
      value: "true"
    - name: AVREGNING_LISTENER_ENABLED
      value: "true"

    # PDL
    - name: PDL_URL
      value: "https://pdl-api.intern.nav.no"
    - name: PDL_SCOPE
      value: "api://prod-fss.pdl.pdl-api/.default"

    # SFTP
    - name: SFTP_SERVER
      value: sftp.oera.no
    - name: SFTP_PORT
      value: "22"
    - name: SFTP_PRIVATE_KEY_FILE_PATH
      value: /var/run/secrets/spk-sftp-private-key/spk-sftp-private-key

    # DB-SCHEDULER
    - name: SCHEDULER_ENABLED # Settes til true for å aktivere scheduler
      value: "true"
    - name: READ_PARSE_FILE_AND_VALIDATE_TRANSACTIONS_CRON_PATTERN
      value: "0 0 7-17 * * *"
    - name: SEND_UTBETALING_TRANSAKSJON_TIL_OPPDRAGZ_CRON_PATTERN
      value: "0 0 7-17 * * *"
    - name: SEND_TREKK_TRANSAKSJON_TIL_OPPDRAGZ_CRON_PATTERN
      value: "0 0 7-17 * * *"
    - name: GRENSESNITT_AVSTEMMING_CRON_PATTERN
      value: "0 0 5 * * *"
    - name: WRITE_AVREGNINGSRETUR_FILE_CRON_PATTERN
      value: "0 30 6 * * *"