apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-spk-mottak
  namespace: okonomi
  labels:
    team: okonomi
spec:
  image: "{{{ image }}}"
  port: 8080
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  liveness:
    path: /internal/isAlive
    initialDelay: 5
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/isReady
    initialDelay: 5
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      memory: 4096Mi
    requests:
      cpu: 2000m
      memory: 4096Mi
  ingresses:
    - https://sokos-spk-mottak.intern.dev.nav.no
  prometheus:
    enabled: true
    path: /internal/metrics
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  accessPolicy:
    inbound:
      rules:
        - application: azure-token-generator
          namespace: aura
          cluster: dev-gcp
  webproxy: true
  vault:
    enabled: true
  filesFrom:
    - secret: db2license
      mountPath: /var/run/secrets/db2license
    - secret: spk-sftp-private-key
      mountPath: /var/run/secrets/spk-sftp-private-key
    - secret: spk-sftp-host-key
      mountPath: /var/run/secrets/spk-sftp-host-key
  envFrom:
    - secret: spk-sftp-creds
    - secret: oppdrag-qx-credentials
  env:
    - name: USE_AUTHENTICATION
      value: "true"

    # Database
    - name: DATABASE_HOST
      value: "155.55.1.82"
    - name: DATABASE_PORT
      value: "5025"
    - name: DATABASE_NAME
      value: "QDB2"
    - name: DATABASE_SCHEMA
      value: "MO611QX"

    # SFTP
    - name: SFTP_SERVER
      value: b31apvl069.oera-q.local
    - name: SFTP_PORT
      value: "22"
    - name: SFTP_PRIVATE_KEY_FILE_PATH
      value: /var/run/secrets/spk-sftp-private-key/spk-sftp-private-key