package no.nav.sokos.spk.mottak.domain

import java.time.LocalDate
import java.time.LocalDateTime

data class Avregningsretur(
    val returTilAnviserId: Int? = null,
    val rectype: String,
    val returtype: String,
    val anviser: String,
    val osId: String? = null,
    val osLinjeId: String? = null,
    val trekkvedtakId: String? = null,
    val gjelderId: String,
    val fnr: String? = null,
    val datoStatus: LocalDate,
    val status: String,
    val bilagsnrSerie: String,
    val bilagsnr: String,
    val datoFom: LocalDate,
    val datoTom: LocalDate,
    val belop: String,
    val debetKredit: String,
    val utbetalingtype: String,
    val transTekst: String,
    val transEksId: String? = null,
    val datoAvsender: LocalDate,
    val utbetalesTil: String,
    val statusTekst: String? = null,
    val duplikat: Boolean,
    val transaksjonId: Int? = null,
    val filInfoInnId: Int? = null,
    val filInfoUtId: Int? = null,
    val datoValutering: String,
    val konto: String,
    val datoOpprettet: LocalDateTime,
    val opprettetAv: String,
    val datoEndret: LocalDateTime,
    val endretAv: String,
    val versjon: Int,
    val motId: String? = null,
    val personId: String? = null,
    val kreditorRef: String? = null,
)
