package no.nav.sokos.spk.mottak.domain

const val SPK = "SPK"
const val NAV = "NAV"

// FILETYPE
const val FILTYPE_ANVISER = "ANV"
const val FILTYPE_INNLEST = "INL"

// FILTILSTANDTYPE
const val FILTILSTANDTYPE_AVV = "AVV"
const val FILTILSTANDTYPE_GOD = "GOD"
const val FILTILSTANDTYPE_INN = "INN"
const val FILTILSTANDTYPE_RET = "RET"
const val FILTILSTANDTYPE_KTR = "KTR"

// TRANSAKSJONTYPE
const val TRANSAKSJONSTATUS_OK = "00"

// RECTYPE
const val RECTYPE_STARTRECORD = "01"
const val RECTYPE_TRANSAKSJONSRECORD = "02"
const val RECTYPE_SLUTTRECORD = "09"

// BEHANDLET
const val BEHANDLET_NEI = "N"
const val BEHANDLET_JA = "J"

// BELOPTYPE
const val BELOPTYPE_SKATTEPLIKTIG_UTBETALING = "01"
const val BELOPTYPE_IKKE_SKATTEPLIKTIG_UTBETALING = "02"
const val BELOPTYPE_TREKK = "03"

// TRANSAKSJON TOLKNING
const val TRANS_TOLKNING_NY = "NY"
const val TRANS_TOLKNING_NY_EKSIST = "NY_EKSIST"

// FNR ENDRET
const val FNR_ENDRET = '1'
const val FNR_IKKE_ENDRET = '0'

// TRANSAKSJON TILSTAND STATUS
const val TRANS_TILSTAND_OPR = "OPR"

// TREKK ANSVAR
const val TREKKANSVAR_4819 = "4819"

// ANVISER FIL BESKRIVELSE
const val ANVISER_FIL_BESKRIVELSE = "Innlesingsretur"
