package no.nav.sokos.spk.mottak.domain

const val SPK = "SPK"
const val NAV = "NAV"

// FILETYPE
const val FILETYPE_ANVISER = "ANV"

// FILTILSTANDTYPE
const val FILTILSTANDTYPE_AVV = "AVV"
const val FILTILSTANDTYPE_GOD = "GOD"
const val FILTILSTANDTYPE_INN = "INN"
const val FILTILSTANDTYPE_RET = "RET"
const val FILTILSTANDTYPE_KTR = "KTR"

// TRANSAKSJONTYPE
const val TRANSAKSJONSTATUS_OK = "00"

// RECTYPE
const val RECTYPE_STARTRECORD = "01"
const val RECTYPE_TRANSAKSJONSRECORD = "02"
const val RECTYPE_SLUTTRECORD = "09"

// BEHANDLET
const val BEHANDLET_NEI = "N"

// BELOPTYPE
const val BELOPTYPE_SKATTEPLIKTIG_UTBETALING = "01"
