package no.nav.sokos.spk.mottak.domain

import java.time.LocalDate
import java.time.LocalDateTime

data class Transaksjon(
    val transaksjonId: Int? = null,
    val transaksjonTilstandId: Int? = null,
    val filInfoId: Int,
    val transaksjonStatus: String,
    val personId: Int,
    val beloptype: String,
    val art: String,
    val anviser: String,
    val fnr: String,
    val utbetalesTil: String,
    val osId: String? = null,
    val osLinjeId: String? = null,
    val datoFom: LocalDate,
    val datoTom: LocalDate,
    val datoAnviser: LocalDate,
    val datoPersonFom: LocalDate,
    val datoLeakFom: LocalDate,
    val belop: Int,
    val refTransId: String,
    val tekstkode: String,
    val rectype: String,
    val transEksId: String,
    val transTolkning: String,
    val sendtTilOppdrag: String,
    val trekkvedtakId: String? = null,
    val fnrEndret: Boolean,
    val motId: String,
    val osStatus: String? = null,
    val datoOpprettet: LocalDateTime,
    val opprettetAv: String,
    val datoEndret: LocalDateTime,
    val endretAv: String,
    val versjon: Int,
    val saldo: Int,
    val kid: String,
    val prioritet: LocalDate?,
    val trekkansvar: String,
    val transTilstandType: String,
    val grad: Int?
)