name: Build & test PR (frontend)

on:
  pull_request:
    paths-ignore:
      - 'backend/**'
      - 'frontend/.gitignore'
      - 'frontend/.nais/**'
      - '**.md'
      - 'LICENCE'
      - 'CODEOWNERS'
      - '.github/workflows/*-backend.yaml'
      - '.github/workflows/deploy-frontend.yaml'
      - '.github/workflows/digestabot-automerge.yaml'
      - '.github/workflows/digestabot-update.yaml'
      - 'dependabot-automerge.yaml'
      - '.github/workflows/manual-deploy-frontend.yaml'
      - '.github/workflows/codeql-scan-frontend.yaml'
      - '.github/dependabot.yaml'

env:
  TZ: Europe/Oslo

jobs:
  build-test-pr:
    permissions:
      contents: read
    name: Build & test application
    uses: navikt/mob-gha-workflows/.github/workflows/node-build-pr.yaml@ef9d193067cf5fcce3a63ebb53c7cda7ef9c2541 # ratchet:navikt/mob-gha-workflows/.github/workflows/node-build-pr.yaml@v1.2.0
    secrets: inherit
    with:
      project-directory: frontend
