name: Build & test PR (backend)

on:
  pull_request:
    paths-ignore:
      - 'frontend/**'
      - 'backend/.gitignore'
      - 'backend/.editorconfig'
      - 'backend/setupLocalEnvironment.sh'
      - 'backend/.scripts/**'
      - 'backend/.nais/**'
      - '**.md'
      - 'LICENCE'
      - 'CODEOWNERS'
      - '.github/workflows/*-frontend.yaml'
      - '.github/workflows/codeql-scan-backend.yaml'
      - '.github/workflows/deploy-backend.yaml'
      - '.github/workflows/digestabot-automerge.yaml'
      - '.github/workflows/digestabot-update.yaml'
      - '.github/workflows/manual-deploy-backend.yaml'
      - '.github/dependabot.yaml'

env:
  TZ: Europe/Oslo

jobs:
  build-and-test:
    permissions:
      contents: read
    uses: navikt/mob-gha-workflows/.github/workflows/gradle-build-test-app.yaml@eeb9163c47db1ceaadebd3130fa5f03c0fbf0b45 # ratchet:navikt/mob-gha-workflows/.github/workflows/gradle-build-test-app.yaml@v1.2.1
    with:
      project-directory: backend
