name: Build & test PR (backend)

on:
  pull_request:
    paths-ignore:
      - 'frontend/**'
      - 'backend/.gitignore'
      - 'backend/.editorconfig'
      - 'backend/setupLocalEnvironment.sh'
      - 'backend/.scripts/**'
      - 'backend/.nais/**'
      - '**.md'
      - 'LICENCE'
      - 'CODEOWNERS'
      - '.github/workflows/*-frontend.yaml'
      - '.github/workflows/codeql-scan-backend.yaml'
      - '.github/workflows/deploy-backend.yaml'
      - '.github/workflows/digestabot-automerge.yaml'
      - '.github/workflows/digestabot-update.yaml'
      - '.github/workflows/manual-deploy-backend.yaml'
      - '.github/dependabot.yaml'

env:
  TZ: Europe/Oslo

jobs:
  build-and-test:
    permissions:
      contents: read
    uses: navikt/beregningsplattform-gha-workflows/.github/workflows/gradle-build-test-app.yaml@d9f047707da888caa7b9ba04a7716eb2f3564f27 # ratchet:navikt/beregningsplattform-gha-workflows/.github/workflows/gradle-build-test-app.yaml@v1.1.0
    with:
      project-directory: backend
